# Generated by Django 5.1.7 on 2025-11-30 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_order_codigo_postal_order_costo_envio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código único (ej: MANOLITO)', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del código (ej: Código de Manolito)', max_length=200)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (ej: 10.00 para 10%)', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha desde cuando es válido', null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha hasta cuando es válido', null=True)),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Máximo de usos totales (dejar vacío para ilimitado)', null=True)),
                ('usos_por_usuario', models.PositiveIntegerField(default=1, help_text='Máximo de usos por usuario')),
                ('usos_actuales', models.PositiveIntegerField(default=0, editable=False)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo de compra requerido', max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Descuento',
                'verbose_name_plural': 'Códigos de Descuento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UsoCodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('monto_descuento', models.DecimalField(decimal_places=2, help_text='Monto del descuento aplicado', max_digits=10)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='market.codigodescuento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_usados', to='market.order')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Código',
                'verbose_name_plural': 'Usos de Códigos',
                'ordering': ['-fecha_uso'],
            },
        ),
    ]
