# Generated by Django 5.2 on 2025-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_codigodescuento_usocodigodescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_confirmacion_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='email_confirmacion_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
