# Generated by Django 5.2 on 2025-12-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order_email_confirmacion_enviado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email_confirmacion_enviado',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email_confirmacion_fecha',
        ),
    ]
