# Generated by Django 5.2 on 2025-12-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_order_email_confirmacion_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_invitado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nombre_invitado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='telefono_invitado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
