# Generated by Django 5.2 on 2025-12-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_order_email_invitado_order_nombre_invitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apellido_invitado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
